In [1]:
from selenium import webdriver
from selenium.webdriver.support.ui import Select
from time import*
browser = webdriver.Chrome()
url = "http://rate.am/en/armenian-dram-exchange-rates/banks/non-cash"
browser.get(url)
data=browser.find_element_by_xpath('//*[@id="aspnetForm"]/div[3]/div[2]/div[1]/div[4]/div[3]/table/tbody/tr/td[1]/a')
data.click()

In [2]:
year = browser.find_element_by_xpath('//*[@id="calBorder"]/span/table/tbody/tr[1]/td/table/tbody/tr/td[2]/select')
sy = Select(year)
sy.select_by_visible_text('2016')

In [3]:
month = browser.find_element_by_xpath('//*[@id="calBorder"]/span/table/tbody/tr[1]/td/table/tbody/tr/td[1]/select')
sm = Select(month)
sm.select_by_visible_text('July')

In [4]:
data1=browser.find_element_by_xpath('//*[@id="calBorder"]/span/table/tbody/tr[3]/td/table/tbody/tr[5]/td[3]')
data1.click()

In [5]:
data2=browser.find_element_by_xpath('//*[@id="ctl00_Content_RB_dtpick1_btnOk"]')
data2.click()

In [6]:
import pandas as pd
import csv
opt = pd.read_html(browser.find_element_by_class_name("rb").get_attribute('outerHTML'))
opt= opt[0]
opt = opt[2:19]
del opt[0]
del opt[2]
del opt[3]
opt.columns = ["name", "date", "USD_buy", "USD_sell", "EUR_buy", "EUR_sell", "RUB_buy", "RUB_sell", "GBP_buy", "GBP_sell"]
from unicodecsv import*
with open('datadata.csv', 'w') as f:
            opt.to_csv(f, header=True, index=False, encoding='utf-8')

In [7]:
opt

,name,date,USD_buy,USD_sell,EUR_buy,EUR_sell,RUB_buy,RUB_sell,GBP_buy,GBP_sell
2,Էյչ-Էս-Բի-Սի Բանկ,"20 Jul, 20:00",473.50,478.50,519,529.0,7.36,7.67,618.5,630.5
3,Յունիբանկ,"20 Jul, 20:00",473.50,478,519,531.0,7.40,7.80,610.0,640.0
4,Կոնվերս բանկ,"20 Jul, 20:00",475,478,520,527.0,7.43,7.77,619.0,628.0
5,ՀԱՅԲԻԶՆԵՍԲԱՆԿ ՓԲԸ,"20 Jul, 20:00",474,477,520.10,527.1,7.41,7.67,617.1,629.1
6,Անելիք Բանկ,"20 Jul, 20:00",474,477.50,517,528.0,7.35,7.65,NaN,NaN
7,Արդշինբանկ,"20 Jul, 20:00",474,478,518,530.0,7.35,7.65,615.0,645.0
8,ԱՐԱՐԱՏԲԱՆԿ,"20 Jul, 20:00",474,477.50,516,530.0,7.40,7.75,616.0,633.0
9,ՎՏԲ-Հայաստան Բանկ,"20 Jul, 20:00",474,477.50,519,525.5,7.42,7.55,618.0,630.0
10,ՀԱՅԷԿՈՆՈՄԲԱՆԿ,"20 Jul, 20:00",473.50,477.50,517,527.0,7.43,7.80,616.0,642.0
11,Ամերիաբանկ,"20 Jul, 20:00",473.50,477.50,519,529.0,7.37,7.62,621.5,631.5
12,Արմսվիսբանկ,"20 Jul, 20:00",474.50,477.50,521,528.0,7.42,7.62,620.0,628.0
13,ԱԿԲԱ-ԿՐԵԴԻՏ ԱԳՐԻԿՈԼ ..,"20 Jul, 20:00",473.50,477.50,519.50,527.5,7.43,7.59,620.0,635.0
14,Արցախբանկ,"20 Jul, 20:00",475,478,520,528.0,7.35,7.70,616.0,631.0
15,Պրոմեթեյ Բանկ,"20 Jul, 20:00",475,477,521,527.0,7.44,7.67,619.0,629.0
16,Ինեկոբանկ,"20 Jul, 20:00",475,477.75,519.50,527.5,7.38,7.60,619.0,633.0
17,Մելլաթ բանկ,"20 Jul, 20:00",473.50,477.50,519,529.0,NaN,NaN,NaN,NaN
18,Բիբլոս Բանկ Արմենիա,"20 Jul, 20:00",474,478.50,519,530.0,7.38,7.65,615.0,634.0